apiVersion: v2
name: coralogix-opentelemetry-integration
description: OpenTelemetry barebones to have Coralogix Kubernetes Monitoring working out-of-the-box.
version: 0.7.0
kubeVersion: ">=1.16.0-0"
keywords:
  - OpenTelemetry Collector
  - OpenTelemetry Agent
  - Kubernetes
  - Coralogix
dependencies:
  - name: opentelemetry-collector
    alias: opentelemetry-collector-agent
    version: "0.64.0"
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: opentelemetry-collector-agent.enabled
  - name: opentelemetry-collector
    alias: opentelemetry-collector-events
    version: "0.64.0"
    repository: https://open-telemetry.github.io/opentelemetry-helm-charts
    condition: opentelemetry-collector-events.enabled
  - name: kube-state-metrics
    version: "5.8.1"
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-state-metrics.enabled
sources:
  - https://github.com/open-telemetry/opentelemetry-helm-charts/tree/main/charts/opentelemetry-collector
maintainers:
  - name: Coralogix
    email: platform@coralogix.com
