name: coralogix-opentelemetry-integration

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Chart.yaml
      - Chart.yaml
      - values.yaml

env:
  CHART_VERSION: $(yq eval '.version' Chart.yaml)
  CHART_NAME: coralogix-opentelemetry-integration
  ARTIFACTORY_URL: https://cgx.jfrog.io/artifactory/
  ARTIFACTORY_USERNAME: integrations-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Setup Helm Repo
        run: |
          helm repo add opentelemetry https://open-telemetry.github.io/opentelemetry-helm-charts
          helm repo update
          helm dependency build .
          helm package .
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2.1.0
        with:
          version: 2.12.1
      - name: use-jfrog-cli
        run: |
          jfrog rt upload --access-token ${{ secrets.ARTIFACTORY_NONUSER_ACCESS_TOKEN }} "${{ env.CHART_NAME }}-*.tgz" coralogix-charts --url ${{ env.ARTIFACTORY_URL }}
